[workspace]
resolver = "2"

members = [
  "prerelease-only-1-0-0",
  "prerelease-ahead-major",
  "prerelease-ahead-minor",
  "prerelease-ahead-patch",
  "prerelease-matches-stable-0-1-0",
  "prerelease-matches-stable-1-0-0",
]
